### ISSUE TITLE
add /me command

### ISSUE THREAD

**Issue by dola** [SimpleServer/SimpleServer#143]
either natively to SimpleServer or default forward it

**Comment by jones77** [comment]
If you give this no arguments I think it clashes the client (1.0.0):

Exception in thread "PlayerStream-thejones77" java.lang.NullPointerException
        at simpleserver.command.MeCommand.execute(MeCommand.java:35)
        at simpleserver.Player.parseCommand(Player.java:524)
        at simpleserver.stream.StreamTunnel.handlePacket(StreamTunnel.java:308)
        at simpleserver.stream.StreamTunnel.access$300(StreamTunnel.java:50)
        at simpleserver.stream.StreamTunnel$Tunneler.run(StreamTunnel.java:1238)

**Comment by jones77** [comment]
*crashes :-)

**Comment by jones77** [comment]
31   public void execute(Player player, String message) {
 32     String msg = extractArgument(message);
 33     String messagePattern = player.getServer().config.properties.get("meCommandFormat");
 34
 35     String space = msg.startsWith("'") ? "" : " ";
 36     player.sendMessage(String.format(messagePattern, player.getName(), msg, space), false);
 37   }

Line 35 is probably dereferencing a null pointer ...

**Comment by dola** [comment]
yeah that's true :D and you even found the exact position where the error occurs... nice :) thanks. will fix this
