### ISSUE TITLE
Chat crash

### ISSUE THREAD

**Issue by NiLon** [SimpleServer/SimpleServer#245]
When you send max lenght message in chat that contain no spaces you get StackOverflowError.

Exception in thread "ServerStream-PLAYERNAME" java.lang.StackOverflowError
        at simpleserver.stream.StreamTunnel.write(Unknown Source)
        at simpleserver.stream.StreamTunnel.write(Unknown Source)
        at simpleserver.stream.StreamTunnel.sendMessagePacket(Unknown Source)
        at simpleserver.stream.StreamTunnel.sendMessage(Unknown Source)
        at simpleserver.stream.StreamTunnel.sendMessage(Unknown Source)
        ...

**Comment by dola** [comment]
I couldn't reproduce it ingame and cannot find the bug in the code. But I suggest, that we remove the chat wrapping anyway since it seems that the new versions of minecraft do it automatically on clientside. But first we have to explore what happens with unexpected lengths of messages (e.g. when sent directly and not over the client).

**Comment by NiLon** [comment]
Maybe it's spefic config that causes this?

```
<property name="forwardChat">false</property>
<property name="logMessageFormat">%1$s-&gt;%2$s\: %3$s</property>
<property name="logMessages">true</property>
<property name="msgFormat">§%3$s&lt;%1$s&gt; §f</property>
<property name="msgTitleFormat">§%3$s[%2$s]&lt;%1$s&gt; §f</property>
<property name="msgWrap">false</property>
<property name="useMsgFormats">true</property>
```

User that said this had colored name without title.

Actually, I did add space to msgFormat, maybe it does exceed limit (if there is such) by 1 byte because of that?
