### ISSUE TITLE
Backup script sometimes failing - bug

### ISSUE THREAD

**Issue by lucifer6642** [SimpleServer/SimpleServer#254]
Occasionally both automatic and manually forced backups fail to complete.

This appears in the console window for the server

```
Exception in thread "AutoBackup" java.lang.IllegalArgumentException: world\level.dat_new does not exist
        at org.apache.commons.io.FileUtils.sizeOf(Unknown Source)
        at org.apache.commons.io.FileUtils.sizeOfDirectory(Unknown Source)
        at simpleserver.thread.AutoFreeSpaceChecker.check(Unknown Source)
        at simpleserver.thread.AutoBackup$Archiver.run(Unknown Source)
```

After this happens, no other backups function and on stopping the server, simpleserver continues to run until the process is manually killed.

Currently running simpleserver compiled from git on 2012-04-05 and Minecraft 1.2.5

**Comment by dola** [comment]
This most likely happens if SimpleServer is trying to calculate the backup size while the vanilla server is saving some files or if SimpleServer doesn't have permission to copy or access the file `level.dat_new`. I'll check if it's better to disable the saving before the size calculation process instead of waiting for that until the real backup happens.
