### ISSUE TITLE
org.xml.sax.SAXException: Found unknown tag "config"

### ISSUE THREAD

**Issue by TunkDesign** [SimpleServer/SimpleServer#310]
Hello,

When trying to incorporate your code into a personal project I get the following error on startup;

_Note: The source code is no different from the repo here._
_But if you still want the source code of_ **XMLTagResolver.java** _and_ **XMLTag.java** _, here you go:_
**XMLTag.java; http://pastebin.com/7iuqFSfj**
**XMLTagResolver.java; http://pastebin.com/RhSMYSVT**

``` java
SimpleServer -- Copyright (C) 2011 SimpleServer authors (see CONTRIBUTORS)
This program is licensed under The MIT License.
See file LICENSE for details.
>> Starting SimpleServer 8.4.3
[SimpleServer] Error while loading default config.xml
org.xml.sax.SAXException: Found unknown tag "config"
    at com.TunkDesign.NeManager.Wrapper.packets.server.config.xml.XMLTagResolver.getTag(XMLTagResolver.java:84)
    at com.TunkDesign.NeManager.Wrapper.packets.server.config.xml.XMLTagResolver.startElement(XMLTagResolver.java:34)
    at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
    at org.apache.xerces.impl.dtd.XMLDTDValidator.startElement(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
    at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at com.TunkDesign.NeManager.Wrapper.packets.server.config.xml.GlobalConfig.load(GlobalConfig.java:96)
    at com.TunkDesign.NeManager.Wrapper.packets.server.config.xml.GlobalConfig.loadDefaults(GlobalConfig.java:86)
    at com.TunkDesign.NeManager.Wrapper.packets.server.config.xml.GlobalConfig.<init>(GlobalConfig.java:40)
    at com.TunkDesign.NeManager.Wrapper.packets.server.Server.initialize(Server.java:380)
    at com.TunkDesign.NeManager.Wrapper.packets.server.Server.access$200(Server.java:52)
    at com.TunkDesign.NeManager.Wrapper.packets.server.Server$Listener.run(Server.java:515)
[SimpleServer] Syntax error in config.xml! Config was not reloaded.
[SimpleServer] Syntax error in config.xml! Emergency shutdown...
Java Result: 1
BUILD SUCCESSFUL (total time: 0 seconds)
```

**Here's the config.xml file; http://pastebin.com/iDpD8hNS**
**Here's the config.dtd file; http://pastebin.com/W6V6dtQu**

Help to solve this would be appreciated.

Regards.

**Comment by iBotPeaches** [comment]
This isn't a problem in Vanilla SimpleServer. As far as I'm concerned this is a problem during your merge.

Due to the low amount of activity and small amount of resources, I'm closing this to focus on real vanilla bugs.
