### ISSUE TITLE
Broken pipe on disconnect

### ISSUE THREAD

**Issue by blaubaer** [SimpleServer/SimpleServer#32]
If player disconnects from the server, the server prodcuces:

[SimpleServer] java.io.EOFException
[SimpleServer] PlayerStream error handling traffic for xxx.xxx.xxx.xxx
[SimpleServer] java.net.SocketException: Broken pipe
[SimpleServer] ServerStream error handling traffic for xxx.xxx.xxx.xxx
[SimpleServer] Socket Closed: xxx.xxx.xxx.xxx
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:168)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:218)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:235)
        at java.io.FilterInputStream.read(FilterInputStream.java:66)
        at gq.a(SourceFile:131)
        at ji.g(SourceFile:197)
        at ji.c(SourceFile:18)
        at oq.run(SourceFile:85)
2011-05-27 22:09:08 [INFO] xxxxxxxxxx lost connection: disconnect.genericReason

...and if someone tries to reconnect in a few seconds, the player got "Player already on Server." in the client.

**Comment by heapoutofspace** [comment]
This is an error in the new minecraft server and has nothing to do with SimpleServer.
