### ISSUE TITLE
/setgroup PLAYER GROUP fails

### ISSUE THREAD

**Issue by pimanac** [SimpleServer/SimpleServer#53]
Any use of the /setgroup command by owner results in being unable to chat.  you can type things, but they do not appear in the chat window.  Subsequent commands no longer work.  Logging out and back in again fixes that problem.
Backtrace below

Exception in thread "PlayerStream-pimanac" java.lang.IllegalArgumentException: prepareAdd: Passed in key must contain a whitespace!
        at org.apache.commons.configuration.tree.xpath.XPathExpressionEngine.prepareAdd(XPathExpressionEngine.java:223)
        at org.apache.commons.configuration.HierarchicalConfiguration.addPropertyDirect(HierarchicalConfiguration.java:371)
        at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.addPropertyDirect(AbstractHierarchicalFileConfiguration.java:140)
        at org.apache.commons.configuration.HierarchicalConfiguration.setProperty(HierarchicalConfiguration.java:749)
        at org.apache.commons.configuration.AbstractHierarchicalFileConfiguration.setProperty(AbstractHierarchicalFileConfiguration.java:158)
        at simpleserver.config.PermissionConfig.setPlayerGroup(PermissionConfig.java:248)
        at simpleserver.command.SetGroupCommand.setGroup(SetGroupCommand.java:71)
        at simpleserver.command.SetGroupCommand.executeWithTarget(SetGroupCommand.java:65)
        at simpleserver.command.PlayerArgCommand.execute(PlayerArgCommand.java:41)
        at simpleserver.Player.parseCommand(Player.java:339)
        at simpleserver.stream.StreamTunnel.handlePacket(StreamTunnel.java:226)
        at simpleserver.stream.StreamTunnel.access$5(StreamTunnel.java:137)
        at simpleserver.stream.StreamTunnel$Tunneler.run(StreamTunnel.java:1019)

**Comment by vorpalhex** [comment]
Can you confirm the version of SimpleServer you're using? I can't recreate this issue. What syntax are you using?

**Comment by pimanac** [comment]
version 8.1.3 

Syntax used:

/setgroup playersname 4

/setgroup SPACE playersname SPACE 4

I have not changed any of the default group names or id numbers and have entries for each player on the server in the "members" section of the permissions.xml file

From the permissions.xml file
      <group color="f" id="0" ignoreChestlocks="false" name="Guest" showTitle="true"/>
      <group color="f" id="1" ignoreChestlocks="false" name="Player" showTitle="false"/>
      <group color="5" id="2" ignoreChestlocks="false" name="Trusted" showTitle="false"/>
      <group color="9" id="3" ignoreChestlocks="true" name="Mod" showTitle="true"/>
      <group color="6" id="4" ignoreChestlocks="true" name="Admin" showTitle="true"/>
      <group color="3" id="5" ignoreChestlocks="true" name="Owner" showTitle="true"/>

```
  <command allow="0+" name="area"/>
  <command allow="4,5" name="backup"/>
  <command allow="4,5" name="ban"/>
  <command allow="4,5" name="banip"/>
  <command allow="3-5" name="give"/>
  <command allow="4,5" name="giveplayer"/>
  <command allow="3-5" name="gps"/>
  <command aliases="commands" allow="0+" name="help"/>
  <command allow="4,5" name="idbehold"/>
  <command allow="4,5" name="iddqd"/>
  <command allow="3-5" name="kick"/>
  <command aliases="kits" allow="2+" name="kit"/>
  <command allow="3-5" name="listips"/>
  <command aliases="l" allow="0+" name="local"/>
  <command allow="0+" name="localtoggle"/>
  <command allow="1+" name="lock"/>
  <command allow="0+" name="motd"/>
  <command allow="3-5" name="mute"/>
  <command allow="2+" name="myarea"/>
  <command allow="1+" name="mystats"/>
  <command allow="0+" hidden="true" name="ok"/>
  <command allow="5" name="rcon"/>
  <command allow="4,5" forward="true" name="reload"/>
  <command aliases="r" allow="1+" name="reply"/>
  <command allow="4,5" name="restart"/>
  <command allow="0+" name="rules"/>
  <command allow="4,5" forward="true" name="save"/>
  <command allow="0+" name="servertime"/>
  <command allow="4,5" name="setgroup"/>
  <command allow="4,5" name="setipgroup"/>
  <command allow="5" name="stop"/>
  <command aliases="tp" allow="4,5" name="teleport"/>
  <command aliases="t" allow="1+" name="tell"/>
  <command allow="4,5" name="time"/>
  <command allow="4,5" name="unban"/>
  <command allow="4,5" name="unbanip"/>
  <command allow="1+" name="unlock"/>
  <command allow="3-5" name="unmute"/>
  <command allow="3-5" name="unwhitelist"/>
  <command allow="1+" name="visit"/>
  <command allow="3-5" name="warpmeto"/>
  <command allow="3-5" name="warptome"/>
  <command allow="3-5" name="whitelist"/>
  <command aliases="list" allow="0+" name="who"/>
```

**Comment by pimanac** [comment]
Just tested again with version 8.2.1 stable.  This time different error message

permissions.xml here (usernames removed for privacy)
http://pastie.org/2160012

and simpleserver.properties here
http://pastie.org/2160024

Exception in thread "PlayerStream-pimanac" java.lang.IllegalArgumentException: prepareAdd: Passed in key must contain a whitespace!
        at C.B.B.F.A.A.B.B(Unknown Source)
        at C.B.B.F.I.B(Unknown Source)
        at C.B.B.F.M.B(Unknown Source)
        at C.B.B.F.I.C(Unknown Source)
        at C.B.B.F.M.C(Unknown Source)
        at simpleserver.C.O.B(Unknown Source)
        at simpleserver.E.o.B(Unknown Source)
        at simpleserver.E.o.A(Unknown Source)
        at simpleserver.E.D.A(Unknown Source)
        at simpleserver.C.B(Unknown Source)
        at simpleserver.K.D.F(Unknown Source)
        at simpleserver.K.D.C(Unknown Source)
        at simpleserver.K.D$_A.run(Unknown Source)

**Comment by ghost** [comment]
That is actually the same error message. We are just shrinking the class/method names to save space now.
It seems that the error is caused when the player is added to that group... and it somehow fails at `org.apache.commons.configuration.tree.xpath.XPathExpressionEngine.prepareAdd()`... but I am not sure why.

**Comment by pimanac** [comment]
This is working for me as of SimpleServer 8.3.2 beta
